### ISSUE TITLE
Bug using the popup in elementor  - 

### ISSUE THREAD

**Issue by amoyastudio** [RTO-Websites/dynamic-conditions#19]
Hello Great plugin... but i having a bug using the popup in elementor
can't load it only in safe mode because the "the_content" is missing for some reason...

but in the safe mode i can't see the conditions...

**Comment by Enoray** [comment]
Hello @amoyastudio,

sorry for the late response. Can you please give us some more informations?

About the versions (PHP, Elementor, Elementor Pro, DynamicConditions) you use.
How we can reproduce the issue.

Thank you.

**Comment by Enoray** [comment]
No more response &  no other reporting about that issue.

**Comment by amoyastudio** [comment]
Hello sorry for the late response.
the php ver is 7.0
and the elementor is the latest:  Version 2.7.5 
and also the pro latest.
also the latest dynamicConditions ver.

please try to open a popup in elementor and then use the dynamicConditions with GET post check for it the show.

after it.. please save it and get out...
then try to edit the popup with elementor again and you should see the error.

(it's imortant that you use the GET post for the all popup and save it and only then try to edit it again.. )

**Comment by Enoray** [comment]
Hello @amoyastudio, 

i can not reproduce it can you please set up a step by step guide for me?

like:
- create a popup
- add a widget
- dynamic conditions
-- set Dynamic Tag -> RequestParameter, Type -> Get, Parameter Name -> post
-- show/hide -> Show when condition met

and so on.

Thank you very much.

**Comment by amoyastudio** [comment]
NP ... here is a link for the movie i made for it:
it will explain it step by step...

here is the link:
https://drive.google.com/open?id=1u2fH1ZjbShgQTa9x3UCYRquN_0kGpApy

Thank you hope you can fix it.

**Comment by SecretProtonium** [comment]
Fixed in #22 and now on it's way into the master/trunk.

**Comment by Enoray** [comment]
Thanks, seems like we got the issue fixed.

We will publish the fix with our next version. Thank you very much.

**Comment by amoyastudio** [comment]
Great, when will it go out ?? i'm still having issues with it...
can i have the code to change so it will work for now ?

**Comment by crazypsycho** [comment]
Hello, i think this should fix it
https://github.com/RTO-Websites/dynamic-conditions/commit/a695812936c24f50ad85e3dd034a49f34e12ede5

In Public/DynamicConditionsPublic.php just insert on line 244:
```
        if ( ! empty( Plugin::$instance->preview ) && Plugin::$instance->preview->is_preview_mode() ) {
            return;
        }
```

**Comment by amoyastudio** [comment]
Thank you ! working great!
